{% set name = "trustregion" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/trustregion-{{ version }}.tar.gz
  sha256: 93964d09005661c6aad699e8eb4f97590d14a346c70b4037e51d9fc7bfc18ea8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('fortran') }}
  host:
    - numpy
    - pip
    - python
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - trustregion
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lindonroberts/trust-region
  summary: Trust-region subproblem solvers for nonlinear/nonconvex optimization
  license: GPL-3.0-only
  # License file manually packaged. See: https://github.com/lindonroberts/trust-region/pull/5
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Alexis-D
